### ISSUE TITLE
EventEmitter@trigger does not catch parameter properly.

### ISSUE THREAD

**Issue by jtotty** [TomHsiao1260/three-starter#1]
https://github.com/TomHsiao1260/three-starter/blob/87ab8ea0a7ac1d391e1fc7f913d435e3a9d840a4/src/javascript/Utils/EventEmitter.js#L44

This should return `false ` after the console warning. Will throw error when trying to resolve names.

**Comment by TomHsiao1260** [comment]
This bug has been fixed. Thank you very much for checking carefully and making this starter better!
