### ISSUE TITLE
Loading images does not work properly

### ISSUE THREAD

**Issue by Harry-OBrien** [TomHsiao1260/three-starter#11]
Maybe I'm misunderstanding how WebPack is used here, but doing `<img src="../static/some_image.png">` in the HTML source results in the image failing to load. Any ideas?

**Comment by TomHsiao1260** [comment]
Hi, Harry

You should use external assets (e.g. image) via `import` syntax in javascript so that webpack itself could bundle them for you. You can checkout here for more information.
https://webpack.js.org/guides/asset-management/#loading-images

**Comment by TomHsiao1260** [comment]
The solution above using related path (e.g. `./image.png`). If you prefer direct path (e.g. `image.png`), you can put the assets in `static` folder. It will generate the asset in the root directory after each build. For example, there's an image called `cover.png` in static folder. So in javascript, I can call them in the following way without `import` syntax.

```javascript
const myIcon = new Image();
myIcon.src = 'cover.png';

// you can checkout browser console for the image element
document.body.appendChild(myIcon);
```

**Comment by TomHsiao1260** [comment]
You can also run `npm run build` and checkout the `dist` folder to see how webpack manage those assets. Hope it can help :)
